export const strings = {
  app: 'Respiratory Research', home: 'Home', subtitle: 'A foundation for breathing research',
  disclaimer: 'Research prototype. Not for medical diagnosis.',
  simulation: 'Simulation only — no breathing is measured.',
  mockDetail: 'Rate, confidence, and signal quality are fixed example values. They do not describe a person.',
  start: 'Start practice measurement', history: 'Saved history', settings: 'About this prototype',
  newMeasurement: 'New session', participant: 'Participant ID (optional)', age: 'Age in years (optional)',
  notes: 'Notes (optional)', optional: 'Use an anonymous ID. All fields are optional.',
  begin: 'Begin 30-second practice', cancel: 'Cancel', recording: 'Practice session',
  recordingHint: 'Follow the timer to test the workflow. Camera capture will be added after this version is tested.',
  analyzing: 'Preparing simulated result…', result: 'Simulated result', rate: 'Example respiratory rate',
  unit: 'breaths/min', quality: 'Example signal quality', confidence: 'Example confidence',
  save: 'Save practice result', saved: 'Saved to this phone', again: 'Practice again', done: 'Done',
  unusable: 'Unable to measure breathing reliably.', retry: 'Retry session',
  empty: 'No saved sessions yet', emptyHint: 'Complete a practice session and save it to see it here.',
  detail: 'Session details', anonymous: 'Anonymous participant', duration: 'Duration', algorithm: 'Analyzer version',
  date: 'Recorded', delete: 'Delete session', deleteTitle: 'Delete this saved session?',
  deleteBody: 'This removes the session from this phone.', keep: 'Keep session',
  loading: 'Loading…', missing: 'This session is no longer available.',
  storageError: 'Could not load saved sessions. Please try again.', saveError: 'Could not save. Please try again.',
  deleteError: 'Could not delete. Please try again.', analysisError: 'Could not prepare a result. Please retry.',
  ageError: 'Enter a whole age from 1 to 120 years, or leave it blank.',
  idError: 'Keep participant IDs under 81 characters.', notesError: 'Keep notes under 2,001 characters.',
  noSession: 'Start a new practice session to continue.', seconds: 'seconds',
  privacy: 'Sessions stay on this phone. No accounts, uploads, analytics, or permanent video files.',
  roadmap: 'This version tests the app workflow. Camera capture and a validated breathing analyzer are future milestones.',
  developer: 'Developer tools', samples: 'Add five sample sessions', sampleError: 'Could not add samples. Please retry.',
  sampleNotes: 'Developer sample — simulated data.', notProvided: 'Not provided',
  errorTitle: 'Something went wrong', unexpected: 'Please return home and try again.',
  qualities: { good: 'Good ✓', fair: 'Fair', poor: 'Poor !', unusable: 'Unusable !' },
} as const;
